---
- name: Making FB secrets file
  import_playbook: token_create.yml
  vars:
    ansible_user: "{{ fb_user }}"
    ansible_password: "{{ fb_pass }}"

- name: FlashBlade filesystem setup
  hosts: "localhost"
  gather_facts: false
  vars_files:
  - "vars/{{ env }}/fb_details.yml"
  - "vars/{{ env }}/fb_secrets.yml"
  roles:
    - purefb_filesystem_setup

- name: Mount file share on hosts
  hosts: all,!fbgroup
  vars_files:
  - "vars/{{ env }}/fb_details.yml"
  - "vars/{{ env }}/fb_secrets.yml"
  roles:
    - purefb_nfs_mount
