---
- name: Update and install NFS client packages
  block:
  - name: packages | Install NFS client packages on CentOS/RHEL
    yum:
      name: 
        - nfs-utils
        - nfs4-acl-tools
      state: latest
  become: yes
  when: ansible_os_family == "RedHat"

- name: packages | Install updates using apt
  block:
  - name: Update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
    ignore_errors: true

  - name: packages | Install NFS client packages on Ubuntu
    apt:
      name: 
        - nfs-common
        - nfs4-acl-tools
      state: latest
  become: yes
  when: ansible_os_family == "Debian"
